export { FaHeart as IconHeart } from 'react-icons/fa'
export { FaRegHeart as IconHeartFilled } from 'react-icons/fa'
export { FaClock as IconLockClock } from 'react-icons/fa'
export { FaRegClock as IconClock } from 'react-icons/fa'
export { FaRegUser as IconProfile } from 'react-icons/fa'
export { FaUser as IconProfileFilled } from 'react-icons/fa'
export { FcPicture as IconPicture } from 'react-icons/fc'
export { FaCheck as IconCheck } from 'react-icons/fa'
export { FaLink as IconLink } from 'react-icons/fa'
export { IconInstagram } from './IconInstagram'
export { MdChangeHistory as IconChange } from 'react-icons/md'
export { FaUser as IconUser } from 'react-icons/fa'
export { Venus as IconFemale } from 'lucide-react'
export { Mars as IconMale } from 'lucide-react'
export { UserRoundPen as UserRoundPen } from 'lucide-react'
export { ChevronRight as ChevronRight } from 'lucide-react'
export { FaFacebook as IconFacebook } from 'react-icons/fa'
