export { FaHeart as IconHeart } from '../../node_modules/@react-icons/all-files/fa/FaHeart';
export { FaRegHeart as IconHeartFilled } from '../../node_modules/@react-icons/all-files/fa/FaRegHeart';
export { FaClock as IconLockClock } from '../../node_modules/@react-icons/all-files/fa/FaClock';
export { FaRegClock as IconClock } from '../../node_modules/@react-icons/all-files/fa/FaRegClock';
export { FaFemale as IconFemale } from '../../node_modules/@react-icons/all-files/fa/FaFemale';
export { FaMale as IconMale } from '../../node_modules/@react-icons/all-files/fa/FaMale';
export { FaRegUser as IconProfile } from '../../node_modules/@react-icons/all-files/fa/FaRegUser';
export { FaUser as IconProfileFilled } from '../../node_modules/@react-icons/all-files/fa/FaUser';
export { FcPicture as IconPicture } from '../../node_modules/@react-icons/all-files/fc/FcPicture';
export { FaCheck as IconCheck } from '../../node_modules/@react-icons/all-files/fa/FaCheck';
export { FaLink as IconLink } from '../../node_modules/@react-icons/all-files/fa/FaLink';
export { IconInstagram } from './icons/IconInstagram';
export { MdChangeHistory as IconChange } from '../../node_modules/@react-icons/all-files/md/MdChangeHistory';
export { FaUser as IconUser } from '../../node_modules/@react-icons/all-files/fa/FaUser';
