export { FaHeart as IconHeart } from 'react-icons/fa';
export { FaRegHeart as IconHeartFilled } from 'react-icons/fa';
export { FaClock as IconLockClock } from 'react-icons/fa';
export { FaRegClock as IconClock } from 'react-icons/fa';
export { FaFemale as IconFemale } from 'react-icons/fa';
export { FaMale as IconMale } from 'react-icons/fa';
export { FaRegUser as IconProfile } from 'react-icons/fa';
export { FaUser as IconProfileFilled } from 'react-icons/fa';
export { FcPicture as IconPicture } from 'react-icons/fc';
export { FaCheck as IconCheck } from 'react-icons/fa';
export { FaLink as IconLink } from 'react-icons/fa';
export { IconInstagram } from './icons/IconInstagram';
export { MdChangeHistory as IconChange } from 'react-icons/md';
export { FaUser as IconUser } from 'react-icons/fa';
