query getTrack($trackId: Int!) {
	getTrack(trackId: $trackId) {
		artistId
		duration
		link
		id
		preview
		albumPictureUrl
		rank
		title
		id
		title_short
		artist {
			link
			id
			musicGendres
			name
			pictureUrl
		}
	}
}
