query getTracks($artistIds: [BigInt!] = []) {
	getTracks(options: { artistIds: $artistIds }) {
		duration
		preview
		link
		rank
		title_short
		id
		title
		artist {
			link
			name
			pictureUrl
			musicGendres
			id
		}
		artistId
		albumPictureUrl
	}
}
